/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginFormView.java
 *
 * Created on 2010-1-13, 14:49:18
 */
package com.lgh.util.net;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrator
 */
public class LoginFormView extends javax.swing.JFrame {

    /** Creates new form LoginFormView */
    public LoginFormView() {
        initComponents();
        jTextArea1.setAutoscrolls(true);
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 200));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("网页内容"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("用户名:");

        jLabel2.setText("密码:");

        username.setText("lgh3292");

        jButton1.setText("登录");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        password.setText("lghlgh");

        jButton2.setText("登录2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appentURLConnectionContent(HttpURLConnection httpurlconnection) {
        try {
            InputStream is = httpurlconnection.getInputStream();
            Reader r = new InputStreamReader(is, "gbk");
            BufferedReader br = new BufferedReader(r);
            String a = null;
            while ((a = br.readLine()) != null) {
                jTextArea1.append(a + "");
                jTextArea1.append("\n");

            }
        } catch (Exception ex) {
            Logger.getLogger(LoginFormView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user = username.getText();
        String pwd = new String(password.getPassword());
        URL url = null;
        HttpURLConnection httpurlconnection = null;
        try {
            url = new URL("http://www.baidu.com/");
            httpurlconnection = (HttpURLConnection) url.openConnection();
            httpurlconnection.setRequestProperty("User-Agent", "Internet Explorer");
            httpurlconnection.setRequestProperty("Host", "www.baidu.com");
            httpurlconnection.connect();
            int code1 = httpurlconnection.getResponseCode();
            jTextArea1.append("code1:" + code1 + "\n");
            String cookie0 = httpurlconnection.getHeaderField("Set-Cookie");
            jTextArea1.append(cookie0 + "\n");
            appentURLConnectionContent(httpurlconnection);
            httpurlconnection.disconnect();



            url = new URL("http://passport.baidu.com/?login");
            String strPost = "username=" + user + "&password=" + pwd + "&mem_pass=on";
            httpurlconnection = (HttpURLConnection) url.openConnection();
            HttpURLConnection.setFollowRedirects(true);
            httpurlconnection.setInstanceFollowRedirects(true);
            httpurlconnection.setDoOutput(true); // 需要向服务器写数据
            httpurlconnection.setDoInput(true); //
            httpurlconnection.setUseCaches(false); // 获得服务器最新的信息
            httpurlconnection.setAllowUserInteraction(false);
            httpurlconnection.setRequestMethod("POST");
            httpurlconnection.addRequestProperty("Accept",
                    "image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, application/x-shockwave-flash, application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/x-silverlight, */*");
            httpurlconnection.setRequestProperty("Referer",
                    "http://passport.baidu.com/?login&tpl=mn&u=http%3A//www.baidu.com/");
            httpurlconnection.setRequestProperty("Accept-Language", "zh-cn");
            httpurlconnection.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
            httpurlconnection.setRequestProperty("Accept-Encoding", "gzip, deflate");
            httpurlconnection.setRequestProperty("User-Agent",
                    "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; Foxy/1; .NET CLR 2.0.50727;MEGAUPLOAD 1.0)");
            httpurlconnection.setRequestProperty("Host", "passport.baidu.com");
            httpurlconnection.setRequestProperty("Content-Length", strPost.length() + "");
            httpurlconnection.setRequestProperty("Connection", "Keep-Alive");
            httpurlconnection.setRequestProperty("Cache-Control", "no-cache");
            httpurlconnection.setRequestProperty("Cookie", "USERID=13818598e77751707e2a3b");
            httpurlconnection.getOutputStream().write(strPost.getBytes());
            httpurlconnection.getOutputStream().flush();
            httpurlconnection.getOutputStream().close();
            httpurlconnection.connect();
            int code = httpurlconnection.getResponseCode();
            String cookie1 = httpurlconnection.getHeaderField("Set-Cookie");
            jTextArea1.append("code:" + code + "\n");
            jTextArea1.append(cookie1 + "; " + cookie1 + "\n");
            httpurlconnection.disconnect();

            
            url = new URL("http://www.baidu.com");
            httpurlconnection = (HttpURLConnection) url.openConnection();
            httpurlconnection.setRequestProperty("User-Agent", "Internet Explorer");
            httpurlconnection.setRequestProperty("Host", "http://www.baidu.com");
            
//            httpurlconnection.addRequestProperty("Accept",
//            "image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, application/x-shockwave-flash, application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/x-silverlight, */*");
//    httpurlconnection.setRequestProperty("Referer",
//            "http://passport.baidu.com/?login&tpl=mn&u=http%3A//www.baidu.com/");
//    httpurlconnection.setRequestProperty("Accept-Language", "zh-cn");
//    httpurlconnection.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
//    httpurlconnection.setRequestProperty("Accept-Encoding", "gzip, deflate");
//    httpurlconnection.setRequestProperty("User-Agent",
//            "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; Foxy/1; .NET CLR 2.0.50727;MEGAUPLOAD 1.0)");
//    httpurlconnection.setRequestProperty("Host", "passport.baidu.com");
//   
//    httpurlconnection.setRequestProperty("Connection", "Keep-Alive");
//    httpurlconnection.setRequestProperty("Cache-Control", "no-cache");
//    httpurlconnection.setRequestProperty("Cookie", "USERID=13818598e77751707e2a3b");
            httpurlconnection.connect();
            int code3 = httpurlconnection.getResponseCode();
            jTextArea1.append("code3:" + code3 + "\n");
            appentURLConnectionContent(httpurlconnection);
            httpurlconnection.disconnect();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        System.setProperty("http.proxySet", "true");
//        System.setProperty("http.proxyHost", "128.64.191.238");
//        System.setProperty("http.proxyPort", "8080");
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LoginFormView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
